version: "3.8"
services:
  authservice:
    build:
      context: ./authService
      dockerfile: Dockerfile
    container_name: unikeep_authservice
    ports: 
      - "3000:3000"
    depends_on:
      - unikeep_mongodb
    
  unikeep_uploadservice:
    build:
        context: ./uploadService
        dockerfile: Dockerfile
    container_name: unikeep_uploadservice
    image: cungquang1987/cmpt372:unikeep_uploadservice
    ports:
      - "3001:3001"
    environment:
      PORT: 3001
      MONGODB_URI: mongodb://mongoDB372:27017
    depends_on:
      - unikeep_mongodb

  unikeep_asnservice:
    build:
        context: ./asgnService
        dockerfile: Dockerfile
    container_name: unikeep_asnservice
    # image: 
    ports:
      - "3002:3002"
    environment:
      PORT: 3002
      MONGODB_URI: mongodb://mongoDB372:27017
    depends_on:
      - unikeep_mongodb
  
  unikeep_aiService:
    build:
        context: ./aiService
        dockerfile: Dockerfile
    container_name: unikeep_aiService
    image: scott0929/aiservice
    # image:
    ports:
      - "3003:3003"
    environment:
      PORT: 3003
      MONGODB_URI: mongodb://mongoDB372:27017
    depends_on:
      - unikeep_mongodb

  unikeep_mongodb:
    container_name: mongoDB372
    image: mongo:latest       # or specify a specific version like mongo:4.4
    ports:
      - "27017:27017"
    #volume to store & keep data at server level
    volumes:
      - uploadserviceDb:/data/db

#define the volume
volumes:
  uploadserviceDb: {}